// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeeXn1P9hZjLC3EgMqRoCtosqxIuLB4GQ',
    appId: '1:930896839134:web:5f5e9b86a9a6bd6892dd4f',
    messagingSenderId: '930896839134',
    projectId: 'metrogeniusorg-5ddd4',
    authDomain: 'metrogeniusorg-5ddd4.firebaseapp.com',
    storageBucket: 'metrogeniusorg-5ddd4.appspot.com',
    measurementId: 'G-NX8NSFYPKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCibnTHqpI6GGS4oe4MKLJ9c0iz2obDoaw',
    appId: '1:930896839134:android:eae76ce308970e2f92dd4f',
    messagingSenderId: '930896839134',
    projectId: 'metrogeniusorg-5ddd4',
    storageBucket: 'metrogeniusorg-5ddd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnWTpYpEE-kceMsu9JjmM-DEd6g5ftfko',
    appId: '1:930896839134:ios:6a8487f3d9610a9292dd4f',
    messagingSenderId: '930896839134',
    projectId: 'metrogeniusorg-5ddd4',
    storageBucket: 'metrogeniusorg-5ddd4.appspot.com',
    iosBundleId: 'com.example.metrogeniusorg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnWTpYpEE-kceMsu9JjmM-DEd6g5ftfko',
    appId: '1:930896839134:ios:6a8487f3d9610a9292dd4f',
    messagingSenderId: '930896839134',
    projectId: 'metrogeniusorg-5ddd4',
    storageBucket: 'metrogeniusorg-5ddd4.appspot.com',
    iosBundleId: 'com.example.metrogeniusorg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeeXn1P9hZjLC3EgMqRoCtosqxIuLB4GQ',
    appId: '1:930896839134:web:bb9194cc8c45068e92dd4f',
    messagingSenderId: '930896839134',
    projectId: 'metrogeniusorg-5ddd4',
    authDomain: 'metrogeniusorg-5ddd4.firebaseapp.com',
    storageBucket: 'metrogeniusorg-5ddd4.appspot.com',
    measurementId: 'G-FSG6D7KTG3',
  );
}
